### ISSUE TITLE
Refine JSON structures

### ISSUE THREAD

**Issue by kylezinter** [chrisbee32/shufflestream#1]
I will provide more details on what I'll need on the front-end and then @chrisbee32 can implement.

**Comment by kylezinter** [comment]
A channel node: 
Id
Name
Description
ThumbnailUrl { [ ] }
Total number of photos in channel
Created date
Updated date
active

Example channel:
   {
    "channelName": Channel name,
    "description" : Desc
   }

A content node:
id
title
artist
description
active
assetUrl_Ori
assetUrl_L
assetUrl_M
assetUrl_S
artistwebsite
attributelist (hash map)

Example Content:
  {
    "name": Channel name,
    "content" : [{

```
  }]
```

  }

**Comment by ctrlbee** [comment]
Done for the most part. New channel and content object structures are being output to the APIs. The suggested content structure with the channel as a sibling node would have been a total PITA so I skipped it for now. I don't think it's necessary right now since you can get the individual channel content via a query param.
